[deploy]
healthcheckPath = "/health"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[build]
buildCommand = "pip install -r requirements.txt"

[start]
command = "uvicorn main_fixed:app --host 0.0.0.0 --port $PORT"
